spring.application.name=ProductsApplication
server.port=8080

app.name=Products Application
app.default-currency=CRC
app.tax-rate=0.13

spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/products-application-db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=products-application
spring.datasource.password=exA9WvBuGgt9

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true